release-pre:
  stage: build
  image: centos:latest
  rules:
    - if: $CI_COMMIT_TAG                  # Run this job when a tag is created manually
  script:
    - yum update -y && yum install -y git openssh-server
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H "$CI_SERVER_HOST" >> ~/.ssh/known_hosts
    - echo "$SSH_PRIVATE_KEY" | ssh-add - > /dev/null
    - git config --global user.name "CI"
    - git config --global user.email "CI@rescue.rcj.cloud"
    - git remote set-url --push origin git@$CI_SERVER_HOST:$CI_PROJECT_PATH.git
    - ls | grep -v -E 'game|player_controllers|README.md$|CHANGELOG.md$' | xargs rm -r
    - mkdir working
    - mv * working/ -r
    - git pull remote
    - cd remote
    - git checkout release
    - rm *
    - mv ../working/* ./ -r
    - git add *
    - git status
    - ret=$(git status| sed -ne 's|.*\(clean\)|\1|p')
    - if [ -z $ret ];then
    -   git commit -m '[CI] Push by GitLab runner'
    -   git push origin release:release 
    - fi

release_job:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                  # Run this job when a tag is created manually
  script:
    - echo "RELEASE"
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG' # $EXTRA_DESCRIPTION must be defined
    tag_name: '$CI_COMMIT_TAG'
    ref: 'release'