pages:
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - public
  only:
  - master

release_job:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                  # Run this job when a tag is created manually
  script:
    - ls | grep -v -E 'game|player_controllers|README.md$|CHANGELOG.md$' | xargs rm -r
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG' # $EXTRA_DESCRIPTION must be defined
    tag_name: '$CI_COMMIT_TAG'                                      # elsewhere in the pipeline.
    ref: '$CI_COMMIT_TAG'